#:schema node_modules/wrangler/config-schema.json
name = "neo-0"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-08-15"
main = "./app/cloudflare-worker.ts"

[assets]
directory = "./build/client"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]
